[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "alpaca-py>=0.40.1",
    "numpy>=2.3.0",
    "pandas>=2.3.0",
    "requests>=2.32.3",
]
